// <auto-generated />
using GtCores.IdentityCore.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GSites.Migrations.UserSettingsDb
{
    [DbContext(typeof(UserSettingsDbContext))]
    [Migration("20260312091104_UserSettingsMigration")]
    partial class UserSettingsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("GtCores.IdentityCore.Settings.SettingsAdapter", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingValue")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "SettingKey");

                    b.ToTable("core_UserSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
