// <auto-generated />
using GtCores.Extensions.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GSites.Migrations.SettingsDb
{
    [DbContext(typeof(SettingsDbContext))]
    [Migration("20260312090814_SettingsMigration")]
    partial class SettingsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("GtCores.Extensions.Settings.SettingsAdapter", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingValue")
                        .HasColumnType("TEXT");

                    b.HasKey("SettingKey");

                    b.ToTable("core_Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
