// <auto-generated />
using GtCores.Extensions.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GSites.Migrations.SettingsDb
{
    [DbContext(typeof(SettingsDbContext))]
    partial class SettingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("GtCores.Extensions.Settings.SettingsAdapter", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingValue")
                        .HasColumnType("TEXT");

                    b.HasKey("SettingKey");

                    b.ToTable("core_Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
